[package]
name = "iced_winit"
description = "A runtime for iced on top of winit"
version = "0.14.0-dev"
edition = "2021"
authors = ["Héctor Ramón Jiménez <hector@hecrj.dev>"]
license = "MIT"
repository = "https://github.com/iced-rs/iced"
homepage = "https://iced.rs"
categories = ["gui"]
keywords = ["gui", "ui", "graphics", "interface", "widgets"]

[features]
default = ["x11"]
debug = ["iced_runtime/debug"]
system = ["sysinfo"]
program = []
x11 = ["winit/x11"]
wayland = [
    "winit/wayland",
    "cctk",
    "wayland-protocols",
    "raw-window-handle",
    "iced_runtime/wayland",
    "wayland-backend",
    "xkbcommon",
    "xkbcommon-dl",
    "xkeysym",
    "iced_runtime/wayland",
    "wayland-dlopen",
    "wayland-csd-adwaita",
]
wayland-dlopen = ["winit/wayland-dlopen"]
wayland-csd-adwaita = ["winit/wayland-csd-adwaita"]
multi-window = ["iced_runtime/multi-window"]
a11y = ["iced_accessibility", "iced_runtime/a11y"]

[dependencies]
iced_futures = { version = "0.14.0-dev", git = "https://github.com/pop-os/libcosmic.git" }
iced_graphics = { version = "0.14.0-dev", git = "https://github.com/pop-os/libcosmic.git" }
iced_runtime = { version = "0.14.0-dev", git = "https://github.com/pop-os/libcosmic.git" }
iced_accessibility = { version = "0.1", git = "https://github.com/pop-os/libcosmic.git", optional = true, features = ["accesskit_winit"] }
log = "0.4"
rustc-hash = "2.0"
thiserror = "1.0"
tracing = "0.1"
window_clipboard = { git = "https://github.com/pop-os/window_clipboard.git", tag = "pop-0.13-2" }
dnd = { git = "https://github.com/pop-os/window_clipboard.git", tag = "pop-0.13-2" }
winit = { git = "https://github.com/pop-os/winit.git", tag = "iced-xdg-surface-0.13-rc" }
sysinfo = { version = "0.30", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
raw-window-handle = { version = "0.6", optional = true }
cctk = { git = "https://github.com/pop-os/cosmic-protocols", package = "cosmic-client-toolkit", rev = "d0e95be", optional = true }
wayland-protocols = { version = "0.32.1", features = ["staging"], optional = true }
wayland-client = { version = "0.31.5" }
wayland-backend = { version = "0.3.1", features = ["client_system"], optional = true }
xkbcommon = { version = "0.7", features = ["wayland"], optional = true }
xkbcommon-dl = { version = "0.4.1", optional = true }
xkeysym = { version = "0.2.0", optional = true }
rustix = { version = "0.38" }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.69", features = ["Document", "Window", "HtmlCanvasElement"] }
wasm-bindgen-futures = "0.4"

[workspace]
